### PR TITLE
A better defaults PCA change

### PR DESCRIPTION
**Pull request by sstadick**
This is the first option discussed in this issues: https://github.com/petabi/petal-decomposition/issues/22, just making mean-centering optional, but still the default for the general use case. 

I can't for the life of me figure out how to unify the type of the following:

```rust
let x = if self.with_centering {
    input - &mean
} else {
    input
};
```

which would really improve the `inner_fit` methods.

### CODE REVIEW

**Review by msk — COMMENTED** [review]
How about having a constructor that sets `with_centering`? Then `Pca::with_centering(false)` would create an instance that assumes input is centered. With this constructor, `turn_on_mean_centering` and `turn_off_mean_centering` won't be needed since it is unlikely that some inputs are centered and others are not for the same `Pca` instance.

**Comment by sstadick** [comment]
Sure! I'll try something along those lines. I went down that road a bit yesterday but didn't love the fact that for `RandomizedPca` the `with_centering` ends up combining with the `with_rng` / `with_seed` options as well.

**Comment by sstadick** [comment]
@msk, changes made to use constructors instead of setters.

**Comment by msk** [comment]
> I went down that road a bit yesterday but didn't love the fact that for `RandomizedPca` the `with_centering` ends up combining with the `with_rng` / `with_seed` options as well.

You're right. I'll see if I can make `RandomizedPca`'s constructors simpler to blend better with this PR.

**Comment by msk** [comment]
Ended up adopting the builder pattern ([diff](https://github.com/petabi/petal-decomposition/compare/551c8100...82ae4a57)). The following test shows its usage:

```rust
#[test]
fn pca_without_centering() {
    let x = arr2(&[[0_f64, 0_f64], [3_f64, 4_f64], [6_f64, 8_f64]]);
    let mut pca = super::PcaBuilder::new(1).centering(false).build();
    let y = pca.fit_transform(&x).unwrap();
    assert_abs_diff_eq!(y[(0, 0)].abs(), 0., epsilon = 1e-10);
    assert_abs_diff_eq!(y[(1, 0)], 5., epsilon = 1e-10);
    assert_abs_diff_eq!(y[(2, 0)].abs(), 10., epsilon = 1e-10);
}
```

**Comment by sstadick** [comment]
That is much nicer! LMK if there are any other changes you'd like to see to make this work :+1:

**Pull request merged**
